name: Build and Test on Pull Request

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 단계 1: 저장소 체크아웃 -> 작업 디렉토리의 최신 소스코드를 가져옴
      - name: Checkout Repository
        uses: actions/checkout@v2


      # 단계 2: JDK 11 설정 -> JAVA JDK 11로 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'


      # 단계 4: Gradle로 빌드 -> Gradle을 이용하여 스프링 서버 빌드
      - name: Build with Gradle
        run: |
          cd hello-spring
          chmod +x gradlew
          ./gradlew build


      # 도커 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      #도커 이미지 생성 및 푸쉬
      - name: Build and push Docker image
        run: |
          cd hello-spring
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}
          


      # 단계 8: SCP FILE - JAR 파일을 원격 서버로 복사 (서버에 따라 수평확장)
      - name: SCP FILE
        run: |
          cd hello-spring
          scp -i ${{ secrets.PRIVATE_KEY }} -p 22 ${{ secrets.LOCAL_FILE_PATH }} ubuntu@${{ secrets.SERVER1_IP }}:${{ secrets.DESTINATION_FILE_PATH }}
          scp -i ${{ secrets.PRIVATE_KEY }} -p 22 ${{ secrets.LOCAL_FILE_PATH }} ubuntu@${{ secrets.SERVER2_IP }}:${{ secrets.DESTINATION_FILE_PATH }}
          scp -i ${{ secrets.PRIVATE_KEY }} -p 22 ${{ secrets.LOCAL_FILE_PATH }} ubuntu@${{ secrets.SERVER3_IP }}:${{ secrets.DESTINATION_FILE_PATH }}


      # 서버 1 도커 컴포즈 배포
      - name: SSH to SERVER1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd login_practice/hello-spring
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose up -d --remove-orphans  
            

      # 서버 2 도커 컴포즈 배포
      - name: SSH to SERVER2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2_IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd login_practice/hello-spring
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose up -d --remove-orphans  
            

      # 서버 3 도커 컴포즈 배포
      - name: SSH to SERVER3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER3_IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd login_practice/hello-spring
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose up -d --remove-orphans  
