name: Build and Test on Pull Request

on:
  push:
    branches: [dev]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: hello-spring

      - name: Check Current Directory
        run: ls -la hello-spring

      - name: Generate Gradle Wrapper
        run: |
          cd hello-spring
          chmod +x gradlew
          ./gradlew wrapper --gradle-version=7.3.3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle and Run Tests
        run: |
          cd hello-spring
          ./gradlew build test
