name: Build and Test on Pull Request

on:
  push:
    branches: [dev]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        #Checkout

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
        #JAVA JDK 11버전으로 환경설정

      - name: Generate Gradle Wrapper
        run: |
          chmod +x hello-spring/gradlew
          cd hello-spring && ./gradlew wrapper --gradle-version=7.3.3  # Specify the desired Gradle version
        
    

      - name: Build with Gradle
        run: |
          cd hello-spring && ./gradlew build

      - name: Run Tests
        run: |
          cd hello-spring && ./gradlew test
          
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'



      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_PUBLIC_IP }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SCP FILE
        run: |
          cd hello-spring/build/libs && ls
          ls
          echo "SSH Key path: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "SCP Command: scp -i ${{ secrets.SSH_PRIVATE_KEY }} hello-spring-0.0.1-SNAPSHOT.jar ${{ secrets.USERNAME }}@${{ secrets.SSH_PUBLIC_IP }}:/home/ubuntu"
          scp -v -i "${{ secrets.SSH_PRIVATE_KEY }}" hello-spring-0.0.1-SNAPSHOT.jar "${{ secrets.USERNAME }}"@"${{ secrets.SSH_PUBLIC_IP }}":/home/ubuntu

      - name: SSH and Deploy
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" "${{ secrets.SSH_USERNAME }}"@"${{ secrets.SSH_PUBLIC_IP }}" "java -jar /home/ubuntu/hello-spring-0.0.1-SNAPSHOT.jar"
