name: Build and Test on Pull Request

on:
  push:
    brnahces: [ dev ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew wrapper --gradle-version=7.3.3  # Specify the desired Gradle version
          working-directory: $GITHUB_WORKSPACE

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

    # 추가적으로 필요한 단계들을 여기에 추가할 수 있습니다.
